POST:
  post:
    tags:
      - account-service
    parameters:
      - $ref: '../../component/parameter/header.yaml#AppId'
      - $ref: '../../component/parameter/header.yaml#Authorization'
      - $ref: '../../component/parameter/header.yaml#Key'
      - $ref: '../../component/parameter/header.yaml#UserId'
      - $ref: './request/profile-config.yaml#PathProfileId'
    requestBody:
      $ref : './request/profile-config.yaml#BodyPost'
    responses:
      201:
        $ref: './request/profile-config.yaml#Response200'
      400:
        $ref: '../../component/schemas/response/err400.yaml#400BadRequest'
      422:
        $ref: '../../component/schemas/response/err422.yaml#422UnprocessableEntity'
      403:
        $ref: '../../component/schemas/response/err403.yaml#403Forbidden'
      401:
        $ref: '../../component/schemas/response/err401.yaml#401UnAuthorization'
      408:
        $ref: '../../component/schemas/response/err408.yaml#408RequestTimeout'
      404:
        $ref: '../../component/schemas/response/err404.yaml#404NotFound'
      500:
        $ref: '../../component/schemas/response/err500.yaml#500InternalServerError'

GET:
  parameters:
    - $ref: '../../component/parameter/header.yaml#AppId'
    - $ref: '../../component/parameter/header.yaml#Authorization'
    - $ref: '../../component/parameter/header.yaml#Key'
    - $ref: '../../component/parameter/header.yaml#UserId'
    - $ref: './request/profile-config.yaml#PathProfileId'
    - $ref: './request/profile-config.yaml#PathConfigName'
  responses:
    200:
      $ref: './request/profile-config.yaml#Response200'
    400:
      $ref: '../../component/schemas/response/err400.yaml#400BadRequest'
    422:
      $ref: '../../component/schemas/response/err422.yaml#422UnprocessableEntity'
    403:
      $ref: '../../component/schemas/response/err403.yaml#403Forbidden'
    401:
      $ref: '../../component/schemas/response/err401.yaml#401UnAuthorization'
    408:
      $ref: '../../component/schemas/response/err408.yaml#408RequestTimeout'
    404:
      $ref: '../../component/schemas/response/err404.yaml#404NotFound'
    500:
      $ref: '../../component/schemas/response/err500.yaml#500InternalServerError'

PUT:
  parameters:
    - $ref: '../../component/parameter/header.yaml#AppId'
    - $ref: '../../component/parameter/header.yaml#Authorization'
    - $ref: '../../component/parameter/header.yaml#Key'
    - $ref: '../../component/parameter/header.yaml#UserId'
    - $ref: './request/profile-config.yaml#PathProfileId'
    - $ref: './request/profile-config.yaml#PathConfigName'
  requestBody:
    $ref: './request/profile-config.yaml#BodyPut'
  responses:
    200:
      $ref: './request/profile-config.yaml#Response200'
    400:
      $ref: '../../component/schemas/response/err400.yaml#400BadRequest'
    422:
      $ref: '../../component/schemas/response/err422.yaml#422UnprocessableEntity'
    403:
      $ref: '../../component/schemas/response/err403.yaml#403Forbidden'
    401:
      $ref: '../../component/schemas/response/err401.yaml#401UnAuthorization'
    408:
      $ref: '../../component/schemas/response/err408.yaml#408RequestTimeout'
    404:
      $ref: '../../component/schemas/response/err404.yaml#404NotFound'
    500:
      $ref: '../../component/schemas/response/err500.yaml#500InternalServerError'
  
