POST:
  description: |
    - config_value : 
      - MONTHLY_PERIOD: 1 - 29
      - DAILY_NOTIFY: 19:00 Asia/Jakarta | asia/jakarta itu timezone user saat itu, (iana timezone)
      - required: true
    - days : 
      - fieldArray: "monday" or "tuesday" or "wednesday" or "thursday" or "friday" or "saturday" or "sunday" | berdasarkan yang user ceklis
      - required: kalo `DAILY_NOTIFY` true 
    - config_name : 
      - must: `MONTHLY_PERIOD` or `DAILY_NOTIFY`
    - status : 
      - must: `on` or `off`
    - token : 
      - required: true
      - maxLength: 255
  tags:
    - account-service
  parameters:
    - $ref: '../../component/parameter/header.yaml#AppId'
    - $ref: '../../component/parameter/header.yaml#Authorization'
    - $ref: '../../component/parameter/header.yaml#Key'
    - $ref: '../../component/parameter/header.yaml#UserId'
  requestBody:
    $ref : './request/profile-config_request.yaml#BodyPost'
  responses:
    201:
      $ref: './request/profile-config_request.yaml#Response200'
    400:
      $ref: '../../component/schemas/response/err400.yaml#400BadRequest'
    422:
      $ref: '../../component/schemas/response/err422.yaml#422UnprocessableEntity'
    403:
      $ref: '../../component/schemas/response/err403.yaml#403Forbidden'
    401:
      $ref: '../../component/schemas/response/err401.yaml#401UnAuthorization'
    408:
      $ref: '../../component/schemas/response/err408.yaml#408RequestTimeout'
    404:
      $ref: '../../component/schemas/response/err404.yaml#404NotFound'
    500:
      $ref: '../../component/schemas/response/err500.yaml#500InternalServerError'

GET:
  tags:
    - account-service
  parameters:
    - $ref: '../../component/parameter/header.yaml#AppId'
    - $ref: '../../component/parameter/header.yaml#Authorization'
    - $ref: '../../component/parameter/header.yaml#Key'
    - $ref: '../../component/parameter/header.yaml#UserId'
    - $ref: './request/profile-config_request.yaml#PathConfigName'
  responses:
    200:
      $ref: './request/profile-config_request.yaml#Response200'
    400:
      $ref: '../../component/schemas/response/err400.yaml#400BadRequest'
    422:
      $ref: '../../component/schemas/response/err422.yaml#422UnprocessableEntity'
    403:
      $ref: '../../component/schemas/response/err403.yaml#403Forbidden'
    401:
      $ref: '../../component/schemas/response/err401.yaml#401UnAuthorization'
    408:
      $ref: '../../component/schemas/response/err408.yaml#408RequestTimeout'
    404:
      $ref: '../../component/schemas/response/err404.yaml#404NotFound'
    500:
      $ref: '../../component/schemas/response/err500.yaml#500InternalServerError'

PUT:
  description: |
    ### note: config_name diambil dari query parameter dan itu harus `MONTHLY_PERIOD` or `DAILY_NOTIFY`
    - config_value : 
      - MONTHLY_PERIOD: 1 - 29
      - DAILY_NOTIFY: 19:00 Asia/Jakarta | asia/jakarta itu timezone user saat itu, (iana timezone)
      - required: true
    - days : 
      - fieldArray: "monday" or "tuesday" or "wednesday" or "thursday" or "friday" or "saturday" or "sunday" | berdasarkan yang user ceklis
      - required: kalo `DAILY_NOTIFY` true 
    - status : 
      - must: `on` or `off`
    - token : 
      - required: true
      - maxLength: 255
  tags:
    - account-service
  parameters:
    - $ref: '../../component/parameter/header.yaml#AppId'
    - $ref: '../../component/parameter/header.yaml#Authorization'
    - $ref: '../../component/parameter/header.yaml#Key'
    - $ref: '../../component/parameter/header.yaml#UserId'
    - $ref: './request/profile-config_request.yaml#PathConfigName'
  requestBody:
    $ref: './request/profile-config_request.yaml#BodyPut'
  responses:
    200:
      $ref: './request/profile-config_request.yaml#Response200'
    400:
      $ref: '../../component/schemas/response/err400.yaml#400BadRequest'
    422:
      $ref: '../../component/schemas/response/err422.yaml#422UnprocessableEntity'
    403:
      $ref: '../../component/schemas/response/err403.yaml#403Forbidden'
    401:
      $ref: '../../component/schemas/response/err401.yaml#401UnAuthorization'
    408:
      $ref: '../../component/schemas/response/err408.yaml#408RequestTimeout'
    404:
      $ref: '../../component/schemas/response/err404.yaml#404NotFound'
    500:
      $ref: '../../component/schemas/response/err500.yaml#500InternalServerError'
  
