version: '3'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "7171:8080"
    volumes:
      - ./main.yaml:/usr/share/nginx/html/main.yaml
      - ./component:/usr/share/nginx/html/component
      - ./path:/usr/share/nginx/html/path
    environment:
      API_URL: main.yaml

volumes:
  swagger-ui-data: