openapi: '3.0.2'
info:
  title: DUEIT DOCUMENTATION 1.0
  description: |-
    data header:
    - appid = this is app id
    - key = this key
  version: '1.0'
servers:
  - url: https://dueit.my.id/api

tags:
  - name: account-service
    description: ini berkaitan sama profile user
paths:
  /account/{profile-id}:
    $ref: "./path/account-service/account.yaml"

  /account/profile:
    $ref: "./path/account-service/profile.yaml"

  /account/profile-config/{profile-id}:
    $ref: "./path/account-service/profile-config.yaml#/POST"

  /account/profile-config/{profile-id}/{config-name}:
    get:
      tags:
        - account-service
      $ref: "./path/account-service/profile-config.yaml#/GET"
    put:
      tags:
        - account-service
      $ref: "./path/account-service/profile-config.yaml#/PUT"

